### ISSUE TITLE
заменить глифы по эталону

### ISSUE THREAD

**Issue by AlexeyAlexeew** [trufanov-nok/djvudict#4]
Скажите, не смогли бы вы допилить ваш djvudict на такую фичу:
сравнивать получающийся shape с "эталонным" из отдельной папки и заменять его. Я бы заранее нашел и сделал bmp-шки основных алфавитов и кеглей книги, и программа определяла новый шейп - с устанавливаемым уровнем/коэффициентом совпадения - и заменяла старый на новый. И в словаре и в чанке sjbz. Для начала можно попробовать даже refinement-шейпы не трогать. Которые как отклонения записаны.
Вариативности и произвольности не предполагаю, выискивать "инь-эффект" чтоб ошибочные "н" заменить на "и" не нужно. Хочу получить "улучшалку" плохобинаризованных книг, когда книга в целом читаема, но после бинаризации буквы не очень красивые. Хотя возможен вариант что если буква разорвана на куски, то и шейп у нее будет не один, а несколько. Тогда я приплыл.

**Comment by trufanov-nok** [comment]
Пока мне очень сильно не до проектов связанных с djvu. Я даже собраться и опубликовать djvu модуль к stu никак не могу, хотя бы в альфа версии. И ближайший год мне будет не до решения серьезных задач в этих проектах.   
По поводу редактирования словарей я когда-то думал... Что именно я тогда думал, я уже плохо помню...  Поэтому изложу сумбурно. 
Емнип, я считал, что автоматически ничего заменять нельзя. Классификаторы символов в кодировщиках djvu заточены на передачу look&feel входного изображения. Если изображение плохобиноризовано - по хорошему это надо решать на этапе бинаризации. Замена плохобиноризованного на хорошобинаризованное - это уже не задача заменить подобное подобным, а задача заменить подобное чем-то отличающимся в более серьезной степени, чем ожидает имеющийся классификатор. Итого, нужно будет играться с весами или методами сравнения, чтобы сделать новый классификатор, а я уже наигрался всем этим в рамках проекта minidjvu-mod, и не совсем доволен результатом. Поэтому я против автоматизации в этом смысле - проще и надежнее будет сделать ручной редактор. Тогда все что потребуется от djvudict - это замена указанного по id символа словаря на предоставленный пользователем. И это более посильная мне задача.   

_И можно было бы на пальцах посмотреть, а не слишком ли коряво выглядят отредактированные таким образом страницы... потому что такое подозрение у меня есть. Потому что плохобинаризованных вариантов написания одной буквы А на 20 страниц может быть в словаре 10 штук, и замена их всех на 1 эталонный может в конечном итоге бросаться в глаза. Потому что, к примеру, геометрия страницы поползла (или даже дефект оригинальной печати) и все буквы у края страницы на 2 пикселя больше букв у корешка. Начнет плавать положение букв в строке и замены будет бросаться в глаза.   
Вообще, если вы составляете эталонный словарь символов, то можно сделать просто из них шрифт, сделать OCR документа и собрать с этим шрифтом все обратно в doc/pdf. В пределе оно к этому и идет, но это уже будет не оригинальный документ.   
И только если такое редактирование покажется оправданным, то только тогда:_

В качестве GUI можно было бы использовать польский [djview4shapes](https://github.com/jsbien/djview4shapes). Это форк djview4, который использовался для изучения шрифтов средневековых книг. Он умеет выводить глифы словаря  для текущей страницы, подсвечивать их и пр. Но кодовая база там устарела даже по ср с актуальным djview, форк старый. Я им с этим чуть-чуть помогал. В общем, сначала нужно будет актуализировать его состояние. Но не в этом году. Доживем до следующего - там посмотрим.   

P.S. И если кто и будет этим пользоваться, то полтора человека раз в год... В общем, без энтузиазма и очень скептически я на это смотрю.
